baseURL = "https://example.com"
languageCode = "en-us"
title = "StatsMed Sheep"
theme = "hugo-theme-noteworthy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"

[author]
	name = "kimcc"

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "An online journal of statistical, sometimes medical, and often personal musings"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
  twitter = "https://twitter.com/statsmed_sheep"
	linkedin = "https://www.linkedin.com/in/clara~li/"
  github = "https://github.com/statsmed-sheep"
	stackoverflow = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
