---
title: Thank God Yihui Xie is Alive
author: Clara Li
date: '2020-03-16'
slug: thank-god-yihui-xie-is-alive
tags: [
    "techy stuff",
]
draft: yes
---

I was originally going to write an in-depth post on what exactly my process was, getting this site to the (admittedly barebones) structure it is now. But then I realized that 1. I understood maybe 50% of even the simplest tutorials I used, and 2. what you don't understand, you're not very good at explaining. And that makes for a very poor Hugo process blogpost.

Instead, I'd like to turn your attention to Yihui Xie, the R god behind high-powered packages like knitr, bookdown, and blogdown. That last package is what I'm using to write this post right now. Along with Amber Thomas and Alison Presmanes Hill, Xie wrote an awesome online resource called [*blogdown: Creating Websites with R Markdown*](https://bookdown.org/yihui/blogdown/) that comprises 85% of the reason I was able to make StatsMed Sheep. Prior to reading this text, I had some familiarity with Markdown, but little to no experience with the other files mentioned (e.g. `config.toml`, `_site.yml`, etc.). Luckily, Xie, Thomas, and Presmanes Hill wrote a fairly beginner-friendly book that helps cut out the vast majority of what's so difficult about starting to use Hugo and gets right to the core of what you need to know to have a website up and running--maybe not a pretty one, but a website nonetheless. If you want to make your own website using Hugo and blogdown, I highly recommend looking here first.
